### ISSUE TITLE
Wrong usage of jsonObj.getAsJsonObject() on a com.google.gson.JsonNull

### ISSUE THREAD

**Issue by codenox-vs** [SwissSign-AG/RaApi#4]
```java
Exception in thread "main" java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonNull and com.google.gson.JsonObject are in unnamed module of loader 'app')
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:192)
	at org.openapitools.client.model.CertificateOrder.validateJsonObject(CertificateOrder.java:386)
``` 

I found this on (at least) two place and replace it by 

jsonObj.get("xxxxx").isJsonObject()

**Comment by opensource-swisssign** [comment]
Thank you very much for reporting this issue.

Your issue #10 is now considered resolved (d58645f), therefore we’re closing the ticket.

If there is anything else we can support you with, please do not hesitate to contact us.

Have a good day.

Your SwissSign team
